"""initial schema all 10 tables

Revision ID: efc2d1686d72
Revises: 
Create Date: 2026-06-30 05:49:57.607894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc2d1686d72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fii_dii_cash',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('buy_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sell_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'entity_type', name='uq_fii_dii_cash')
    )
    op.create_table('market_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option_chain_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ce_oi', sa.BigInteger(), nullable=True),
    sa.Column('ce_oi_change', sa.BigInteger(), nullable=True),
    sa.Column('ce_ltp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ce_iv', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pe_oi', sa.BigInteger(), nullable=True),
    sa.Column('pe_oi_change', sa.BigInteger(), nullable=True),
    sa.Column('pe_ltp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pe_iv', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pcr', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oc_time_strike', 'option_chain_snapshots', ['snapshot_time', 'strike'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('parent_strategy_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('instrument_token', sa.BigInteger(), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('transaction_type', sa.String(length=5), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trigger_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=50), nullable=True),
    sa.Column('exchange_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('participant_oi',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('client_type', sa.String(length=30), nullable=False),
    sa.Column('long_contracts', sa.BigInteger(), nullable=True),
    sa.Column('short_contracts', sa.BigInteger(), nullable=True),
    sa.Column('long_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('short_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'client_type', name='uq_participant_oi')
    )
    op.create_table('pnl_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('brokerage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('capital_deployed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('roi_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date')
    )
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('instrument_token', sa.BigInteger(), nullable=True),
    sa.Column('option_type', sa.String(length=2), nullable=True),
    sa.Column('strike', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sl_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('fii_oi_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pcr_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chart_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_pain_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pro_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bias', sa.String(length=10), nullable=True),
    sa.Column('raw_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_date')
    )
    op.create_table('strategy_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=True),
    sa.Column('signal_score_id', sa.BigInteger(), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_date')
    )
    op.create_table('system_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_log')
    op.drop_table('strategy_decisions')
    op.drop_table('signal_scores')
    op.drop_table('positions')
    op.drop_table('pnl_daily')
    op.drop_table('participant_oi')
    op.drop_table('orders')
    op.drop_index('idx_oc_time_strike', table_name='option_chain_snapshots')
    op.drop_table('option_chain_snapshots')
    op.drop_table('market_events')
    op.drop_table('fii_dii_cash')
    # ### end Alembic commands ###
